import Head from 'next/head' 
import styles from '@/styles/Home.module.css'  
import axios from 'axios'
import { useEffect, useState, useRef} from 'react' 



export default function Home() {
  const [totalRegistros, setTotalRegistros] = useState(null);

  const [data, setData] = useState([]) 
  const [ atualizaGrid, setAtualizaGrid  ] = useState(false)
  const RotaAtual = 'posts'
  const url = `https://gelatinous-liberating-camp.glitch.me/${RotaAtual}?_page=1&_limit=10`
  
  async function Detalhes(id) {
    await axios.get(url+`${RotaAtual}/${id}`)
    setAtualizaGrid(!atualizaGrid)
  }
 
  
  
  useEffect(() => {
    
    CarregaDados(); 
    console.log( 'Consultou dados novamente e atualizaou conforme a mudança state atualizaGrid: '+ atualizaGrid)
    
    axios.get('http://localhost:3000/api') // { "total": 4 }
    .then(response => {
        setTotalRegistros(response.data.total);
        console.log('puxou o total de registros: ' + totalRegistros)
    }) 



  },[atualizaGrid])

 

 
  async function CarregaDados() {
 
    await axios.get(url+RotaAtual).then(response => setData(response.data))
    data.id ? UltimoIdCadastrado = data.at(-1).id : ''
  
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>Listagem com paginação</h1>
        <div className={styles.center}>
        
        

        {data.map((data) => {
        return(
          <>
          
          <ul key={data.id} >
          
          <li>Id: {data.id}</li>  
          <li>title: {data.title}</li>   
 
          <button onClick={() => Detalhes(data.id)}>Detalhes</button>
          </ul> 
          
          </>
        )
      })}



      {totalRegistros ? (
        <div>
            <p>Total de registros: {totalRegistros}</p> <br/> <br/>
        </div>
        
       ) : (
       <p>Carregando total registros... </p>
       )}

        </div>

      </main>
    </>
  )
}
